version: '3.8'

services:
  app:
    build: .
    container_name: api-website-checker
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - minio
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=checker_db
      - DB_USER=postgres
      - DB_PASSWORD=supersecret123
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniosecretkey
      - MINIO_BUCKET=documents

  db:
    image: postgres:15-alpine
    container_name: checker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: checker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
    ports:
      - "5433:5432"   # host port 5433 biar tidak bentrok jika sudah ada postgres lokal
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: checker-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniosecretkey
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata: